var _tmr=_tmr||[];
(function(){function Mb(a){!Da&&"number"===typeof a&&(Da=a);return V&&Nb&&hb?(ib=[Nb-V,hb-V,Ta?Ta-V:null,Ua?Ua-V:null,Da?Da-V:null].join("/"),Ta&&(Ua&&Da)&&(Mb=function(){return ib}),ib):null}function u(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function N(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Ea(a){return encodeURIComponent(a)}function Ob(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;
if(a.parentNode)return Ob(a.parentNode,b)}catch(c){p&&console.warn("[TopMailRu] Error#1.25",c)}return null}function Pb(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==e.getComputedStyle){var c=e.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function Qb(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]===a)return!0;return!1}function ha(a,b){for(var c=
0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function O(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function ia(a){return"[object Array]"===Object.prototype.toString.call(a)}function ja(){var a=arguments,b=a[0]||{},c=!1,d=1,g=a.length,n,h,m,k,e;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(O(b)||(b={});d<g;d++)if(null!=(n=a[d]))for(h in n)m=b[h],k=n[h],b!==k&&(c&&k&&(O(k)||(e=ia(k)))?(e?(e=!1,m=m&&ia(m)?m:[]):m=m&&O(m)?m:{},b[h]=ja(c,m,k)):void 0!==
k&&(b[h]=k));return b}function Rb(a,b,c){if(!a)return null;var d=a.match(b),g=2<arguments.length?c:0;return d&&d.length>g?d[g]:null}function Sb(a){return(""+a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,"\\$&")}function jb(a){return Rb(a.host,/^(?:w{3}.)?(.*)$/,1)||""}function Hc(a,b,c){a=jb(a);b=(b&&0<b?b:URL_HELPER__MASK_LEVEL)-1;var d=1;a=a.replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Sb(a)+"$";return RegExp(c?"^((?!"+
a+").)*$":a)}function kb(a){var b;if(ia(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(kb(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+Sb(a)+"$");return b.test(jb(y))?null:b}function Tb(a){var b="";try{var c=new Uint8Array(a);e.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(g){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function r(){return(new Date).getTime()}function M(a,b){var c={data:b,raw:a,url:lb(a)},d;if(!Ic||"function"!==
typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var g=mb(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,g)}catch(n){d=!1}}d||(void 0===b?(c.dataSplitter=";",c.open=Jc,c.connect=Kc,c.startListen=Lc,c.stopListen=Mc,c.open(c),c.connect(c)):("function"===typeof e.XMLHttpRequest?(c.dataSplitter=";",c.open=Nc,c.connect=Oc,c.startListen=Pc,c.stopListen=Qc,c.open(c),c.connect(c),d=!0):d=!1,d||Rc(c)))}function Rc(a){var b=f.createElement("iframe"),c=f.createElement("div");c.setAttribute("style",
"position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);try{f.body.appendChild(c)}catch(d){}try{var g=b.contentWindow.document,n=g.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var m=a.data[h],k=typeof m;if("string"===k||"number"===k){var e=g.createElement("input");e.setAttribute("type","hidden");e.setAttribute("name",h);e.value=m;n.appendChild(e)}}var v=g.createElement("form");v.setAttribute("action",
a.url);v.setAttribute("method",Ub);v.setAttribute("enctype",Vb);v.appendChild(n);var s=g.createElement("div");s.appendChild(v);g.body.appendChild(s);var l=function(){try{N(b,"load",l),f.body.removeChild(c)}catch(a){p&&console.warn("[TopMailRu] Error#1.2",a)}};u(b,"load",l);v.submit()}catch(q){p&&console.warn("[TopMailRu] Error#1.3",q)}}function Nc(a){a._connection=new e.XMLHttpRequest}function Oc(a){a._connection.open(Ub,a.url);a._connection.setRequestHeader("Content-Type",Vb);a._connection.send(mb(a.data,
a.dataSplitter))}function Pc(a){u(a._connection,"load",a._onload);u(a._connection,"error",a._onerror)}function Qc(a){N(a._connection,"load",a._onload);N(a._connection,"error",a._onerror)}function Jc(a){a._connection=new Image}function Kc(a){a._connection.src=a.url+mb(a.data,a.dataSplitter)}function Lc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function Mc(a){a._connection.onload=null;a._connection.onerror=null}function mb(a,b){var c=b||";",d="",g;for(g in a)if(a.hasOwnProperty(g)){var n=
a[g],h=typeof n;if("string"===h||"number"===h)d+=c+encodeURIComponent(g)+"="+encodeURIComponent(n)}return d}function lb(a){a="string"===typeof a?a:"/";return"https://top-fwz1.mail.ru"+("/"===a.substring(0,1)?"":"/")+a}function oa(a){return(a=f.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function Fa(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&
(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var g in c)if((b=c[g])||0===b)a+="; "+g,!0!==b&&(a+="="+b);f.cookie=a}function nb(a,b){var c=b||{};c.expires=-1;Fa(a,"",c)}function Sc(){var a="tmr"+(""+Math.random()).slice(2);try{return ka=e.localStorage||null,ka.setItem(a,a),ka.removeItem(a),!0}catch(b){return ka=null,p&&console.warn("[TopMailRu] Error#1.4",b),!1}}function xa(a){try{return ka.getItem(a)}catch(b){p&&console.warn("[TopMailRu] Error#1.5",b)}return null}function Ga(a,
b){try{ka.setItem(a,b)}catch(c){p&&console.warn("[TopMailRu] Error#1.6",c)}}function Tc(){if(!pa)return null;for(var a=y.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var g=1;g<=c;g++)b=a[g]+"."+b;var g=""+r(),n={domain:b,path:"/",expires:3E5};try{Fa("tmr_tcdhn",g,n);var h=oa("tmr_tcdhn");nb("tmr_tcdhn",n);if(h===g)return b}catch(e){p&&console.warn("[TopMailRu] Error#1.8",e)}}return null}function Wb(a,b){pa&&Fa(a,b,ob);qa&&Ga(a,b)}function pb(a,b,c){var d=f.createElement("script");
d.type="text/javascript";d.async=!0;b&&(d.onload=b);c&&(d.onerror=c);d.src=a;try{document.body.appendChild(d)}catch(g){try{c&&c()}catch(n){}}}function Xb(a){var b=";e="+encodeURIComponent("detect");M(B(a,J,!1,!1)+b)}function Yb(a,b){if(a.length&&null!==b.ecom_data){var c=ya(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=qb("_m",b.ecom_method),g=qb("_t",b.ecom_type),n=qb("_jst",Zb()),c="{"+c+d+g+n+"}";M(B({id:a[0]},Uc,!1,!0)+(";ids="+Ea(a.join()))+
(";e="+encodeURIComponent(c)))}}}function qb(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function Vc(){var a=oa($b);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=r()-b;return 0>b||b>ac?null:{id:a[0],version:a[1]}}function bc(a){rb=!0;a.length&&pb(lb("/js/dyn-goal-config.js?ids="+a.join(",")))}function l(){}function Ha(a){a&&"object"===typeof a&&(!P&&"id"in a)&&(P=a.id)}function sb(){var a=0,
b=0;f.documentElement&&(f.documentElement.clientWidth||f.documentElement.clientHeight)?(a=f.documentElement.clientWidth,b=f.documentElement.clientHeight):"number"==typeof e.innerWidth&&(a=e.innerWidth,b=e.innerHeight);return""+a+"*"+b}function Ia(a){return!Va?void 0:Va[a]}function Wc(a){return(a=Ia(a))&&Wa?a-Wa:void 0}function cc(){if(Va){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=
Ia(b[c]);if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function W(a,b){var c=1<arguments.length?b:P;return a&&"object"===typeof a&&("id"in a&&a.id||c)}function dc(a,b,c,d){var g=parseInt(a,10);return isNaN(g)||""+g!==""+a||g<b||g>c?d||0===d?d:null:g}function ec(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return b}return c?a:b}return a||b}function fc(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return"d:"}return c?"e:":"d:"}return a?"e:":"d:"}function gc(a,b,c){if(!a)return b;
if("URL"in window){try{var d=new URL(a);if(d)return a}catch(g){}try{if(d=new URL(a,c))return d.href?d.href:d.toString()}catch(n){}return b}return a}function hc(a,b,c){if(!a)return"d:";if("URL"in window){try{var d=new URL(a);if(d)return"e:"}catch(g){}try{if(d=new URL(a,c))return"h:"}catch(n){}return"d:"}return"e:"}function B(a,b,c,d){qa&&Ga(Ja,++R);var g="id"in a?a.id:P,n=ec(a.url||(X?X:void 0),y.href),h=ec(a.referrer||(Y?Y:void 0),f.referrer),m=gc(a.url||(X?X:void 0),y.href,y.href),k=gc(a.referrer||
(Y?Y:void 0),f.referrer),L="title"in a?a.title:f.title,v;v=tb;null===v&&(v=Xc());v=null!==v?v?1:0:null;var s="userid"in a?a.userid:ba||0===ba?ba:void 0,l=la?la:void 0,q;q=ra&&a.bfCache;var t="pageView"===a.type&&a.timespent,x=[];P&&g!==P&&x.push("sec");"dataLayer"in e&&x.push("dl");Q&&x.push(["ecom"].concat(Q).join("-"));var Aa=Yc();Aa&&Aa.length&&x.push(["jst"].concat(Aa).join("-"));q&&x.push("bfc");Z&&t&&x.push("ts");e.top!==e&&x.push("frame");(!0===G.webdriver||f.$cdc_asdjflasutopfhvcZLmcfl_)&&
x.push("wda");Ka&&x.push.apply(x,Ka);q=x.join(",");var ic,t=(new Date).getTimezoneOffset(),x="";if(e.Intl)try{x=e.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(Zc){p&&console.warn("[TopMailRu] Error#1.1",Zc)}ic=t+"/"+x;var t=jc,t=null!==t?t:Vc(),kc=Mb(a.start),x=lc(),Aa=mc();b=b+"?_="+Math.random()+(g?";id="+encodeURIComponent(g):"")+(m?";u="+encodeURIComponent(m):"")+(k?";r="+encodeURIComponent(k):"")+(n!==m?";u2="+fc(a.url,y.href)+hc(a.url,y.href,y.href):"")+(h!==k?";r2="+fc(a.referrer,
f.referrer)+hc(a.referrer,f.referrer):"");g=dc(a.gender,1,2);b+=null!==g?";gender="+g:"";g=dc(a.age,1,127);d=b+(null!==g?";age="+g:"")+("pid"in a?";pid="+encodeURIComponent(a.pid):"")+(void 0!==s?";userid="+encodeURIComponent(s):"")+(void 0!==l?";uparams="+Ea(ya(l)):"")+(d&&L?";title="+encodeURIComponent(L):"")+(";s="+$c+";vp="+ub+";touch="+ad+";hds="+bd)+";sid="+vb+";ver="+cd+";tz="+encodeURIComponent(ic)+";st="+cc();if(c){if(!Va||!wb)c="";else{c=[];c.push(wb.type);c.push(wb.redirectCount);c.push(Wa);
for(L=0;L<nc.length;L++)c.push(Wc(nc[L]));c=c.join("/")}c=";nt="+c}else c="";c=d+c+(kc?";ct="+kc:"")+(Xa?";rt="+Xa:"")+(Ya?";gl="+Ya:"")+("device"in a?";device="+encodeURIComponent(a.device):"")+";ni=";if(!G||!G.connection)d="";else{d=G.connection;L=[];for(l=0;l<oc.length;l++){s=d[oc[l]];if(void 0!==s)switch(s){case !0:s=1;break;case !1:s=0;break;default:s=(""+s).replace(/\//g,"_")}L.push(s)}d=L.join("/")}return c+d+("params"in a?";params="+Ea(ya(a.params)):"")+(null!==v?";detect="+v:"")+(pa||qa?
";lvid="+Ea([ta,r(),R,ca].join(":")):"")+(q?";opts="+encodeURIComponent(q):"")+(t?";flocid="+encodeURIComponent(t.id)+";flocv="+encodeURIComponent(t.version):"")+(x?";fpid="+encodeURIComponent(x):"")+(Aa?";vkidExtId="+encodeURIComponent(Aa):"")+("version"in a?";appver="+encodeURIComponent(a.version):"")+(ua.support?";visible="+ua.getValue():"")+";js=13"}function xb(a){a=";e="+encodeURIComponent(a);for(var b=0;b<C.length;b++)M(B(C[b],J,!1,!0)+a)}function dd(){tb=!0;pc(1);if(!yb&&!La){La=!0;for(var a=
0;a<C.length;a++)Xb(C[a])}}function ed(){pc(0);tb=!1}function Xc(){var a=oa(qc);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=r()-b;if(0>b||b>rc)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function pc(a){var b=r();a=[a,b].join("|");Fa(qc,a,{path:"/",expires:rc})}function fd(){var a=0;Za&&(a=r()-Za);gd||(z.dcl3=setTimeout(function(){xb("DCL/3")},Math.max(3E3-a,0)))}function hd(){var a=0;$a&&(a=r()-$a);id||(z.pvt2=setTimeout(function(){xb("PVT/2")},Math.max(2E3-
a,0)));jd||(z.pvt15=setTimeout(function(){xb("PVT/15")},Math.max(15E3-a,0)))}function sc(){zb||setInterval(function(){_tmr.beat()},6E4)}function kd(a,b,c,d){if(!b||!d||d===Ab&&b===Ab&&c===Ab)return null;b={goal:ld+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function ab(){Za=r();f.addEventListener?(N(f,"DOMContentLoaded",ab),_tmr.onready()):f.attachEvent&&"complete"===f.readyState&&(N(f,"readystatechange",ab),_tmr.onready());tc()}function Bb(a){$a=r();if(ra){if(a.persisted){Ma=Na=bb=0;
Cb=Db=!1;Z&&E.launch();a=Eb;Eb=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=cb;cb={};for(b in a)_tmr.pageView(a[b]);sc()}}else N(e,"load",Bb);_tmr.onready();_tmr.onload()}function Oa(){ra||(N(e,"unload",Oa),N(e,"beforeunload",Oa));_tmr.unload()}function tc(){Z&&E.launch();if(md){if(!nd&&!uc&&(window.addEventListener("message",function(a){var c=null;try{if(c=a.data,O(c)||(c=Pa(c)),"LOAD_BUTTONS_SCRIPT"===c.type){var d;var g=document.referrer;a=null;var n=[],h=(""+c.lang).toLowerCase();
Qb(h,vc)||(h=vc[0]);n.push(h);"windows-1251"===document.characterSet?n.push("win1251"):"windows-1252"===document.characterSet&&n.push("win1252");try{a=(new URL(g)).host}catch(e){}d=a&&od.test(a)?"https://"+a+"/top_constructor/buttons_"+n.join("_")+".js":lb("/js/dyn-goal-wizard-"+n.join("-")+".js");pb(d)}}catch(k){}}),window.opener))try{window.opener.postMessage({type:"COUNTER_SCRIPT_READY",pageViewIds:va},"*")}catch(a){}rb||(db.push.apply(db,va),bc(va))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var Nb=
(new Date).getTime(),hb=null,Ta=null,Ua=null,Da=null,V=null,ib=null,J="/tracker",Uc="/datalayer",e=window,G=navigator,f=document,y=location,S="string"===typeof y.hostname?y.hostname:"",Qa=-1!=S.search(/(^|\.)odnoklassniki\.ru$/)||-1!=S.search(/(^|\.)ok\.ru$/),wc=-1!=S.search(/(^|\.)vk\.com$/);S.search(/(^|\.)mail\.ru$/);var pd=-1!=S.search(/(^|\.)lamoda\.ru$/),qd=-1!=S.search(/(^|\.)kommersant\.ru$/);S.search(/(^|\.)top\.mail\.ru$/);S.search(/(^|\.)dzen\.ru$/);var nd=-1!=S.search(/^id\.vk\.com$/),
uc=!1;try{uc=-1!=(new URL(f.referrer)).hostname.search(/^id\.vk\.com$/)}catch(Dd){}var xc="string"===typeof y.search&&-1!=y.search.search(/[?&]rb_clickid=/),p="string"===typeof y.search&&-1!=y.search.search(/[?&]tmr_debug=1(?:&|$)/),Ic=!1,zb=Qa||wc||pd||qd,id=!xc,jd=Qa,gd=!xc,yb=!1,Z=e.performance&&"visibilityState"in f,rd=[36383],sd=!(Qa||wc),yc=e.JSON&&e.JSON.stringify&&e.JSON.parse,ra="onpageshow"in e&&"onpagehide"in e,zc="URL"in e,ya=yc?e.JSON.stringify.bind(e.JSON):function(a){return""},Pa=yc?
e.JSON.parse.bind(e.JSON):function(a){return{}},vc=["ru","en"],od=/^((ads\d+\.target\.vk\.ru)|(target\d+\.target\.vk\.ru)|(ads\.vk\.local(:\d+)?))$/,md=zc,Ub="POST",Vb="application/x-www-form-urlencoded",pa=!(0===y.hostname.search(/^(\d+.)+\d+$/g)||-1!==y.hostname.search(/:/g)),ka=null,qa=Sc(),ob={domain:Tc(),path:"/",expires:287712E5};(function(){var a;if(a=f.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,g=a.length;d<g;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&
b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(g=a.length;d<g;d++)b=a[d][0],nb(b,ob)}})();var La=!1,tb=null,rc=864E5,qc="tmr_detect",td=function(){function a(a,b){for(var c=a.length,h,e,k=0;k<b;k++)e=Math.floor(Math.random()*c),h=a[k],a[k]=a[e],a[e]=h;return a.slice(0,b)}function b(b,g){var n=f.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,
50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,
97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);n.setAttribute("class",e.join(" "));n.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");n.setAttribute("id","trg-b-banners-1");
n.setAttribute("data-view","SlotView.mimic");try{this.bait=f.body.appendChild(n)}catch(m){}this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=g||null;var k=this;setTimeout(function(){k._checkBait.call(k)},1)}var c=7;b.prototype._checkBait=function(){if(La)this._stop();else{var a=!1;try{a=null!==f.body.getAttribute("abp")}catch(b){}a||(a=!Pb(this.bait,
!0));(!0===a||10<=++this.loopNumber)&&this._stop();var c;if(a&&this.fnPositive)try{c=this.fnPositive,c()}catch(e){p&&console.warn("[TopMailRu] Error#1.9",e)}else if(!a&&10>this.loopNumber){var m=this;setTimeout(function(){m._checkBait.call(m)},50*this.loopNumber)}else try{c=this.fnNegative,c()}catch(k){p&&console.warn("[TopMailRu] Error#1.10",k)}}};b.prototype._stop=function(){try{f.body.removeChild(this.bait)}catch(a){p&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),
Q=null,Ac="ecommerce",$="dataLayer",Ba=null,Fb=!1,eb=[],ud=[36383,2540645,3171181,3074137,2057653],vd=[],Gb;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var g={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},e=0,n=b.length;e<n;e++){var k=t[b[e]];if(k){a(g.ecom_method,[b[e]]);for(var h=0,m=k.length;h<m;h++)for(var f=0,s=d.length;f<s;f++){var v=k[h][d[f]];if(v)for(var L=0,l=c.length;L<l;L++)if(-1!==k[h].type.indexOf(c[L])){a(g.ecom_type,
[c[L]]);a(g.ecom_data.events,v);break}}}}return g}function c(a,b,c){if(!a||!c||!(b in t))return null;for(var d,g=0,e=t[b].length;g<e;g++)if(d=t[b][g],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],e,h,s=0,v=a.length;s<v;s++)if(h=a[s]){e=null;try{if(h.ecommerce)e=g(h)||n(h);else if(null===h.ecommerce)e=null;else if(h.event){var da={event:h.event,ecommerce:{}};e=g(da)||n(da)}else if("event"===h[0]){var Bc=h[1],wd=h[2],
A=c(Bc,k,l);A&&(A.ecom_data[Bc]=wd);e=A}else if(h.event===Ac)a:{for(var F=b([m],[f],[q]),H=0,w=F.ecom_data.events.length;H<w;H++)if(!h.hasOwnProperty(F.ecom_data.events[H])){e=null;break a}delete F.ecom_data.events;F.ecom_data[Ac]=h;e=F}}catch(t){p&&console.warn("[TopMailRu] Error#1.23",t),e=null}e&&(d.push(e),eb.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Yb(fb,d[a]);Q||(Q=[0,0,$]);Q[0]+=d.length;e=a=0;for(s=d.length;e<s;e++)a+=ya(d[e].ecom_data).length;Q[1]+=a}}function g(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&
(b=c(d,m,v))){if(a.event&&(d=c(a.event,m,s)))for(var g=0,e=b.ecom_type.length;g<e;g++)-1===d.ecom_type.indexOf(b.ecom_type[g])&&(b.ecom_type.splice(g,1),e--,g--);b.ecom_data=a.ecommerce;return b}return null}function n(a){var b=a.event,d=c(b,m,s);d&&(d.ecom_data[b]=a.ecommerce);return d}function h(a){if((a=e[a])&&"function"===typeof a.push)d(a),Ba=a.push,a.push=function(){var a=Ba.apply(this,arguments);d([].slice.call(arguments,0));return a}}var m="push",k="gtag",f="gse",v="inner",s="outer",l="external",
q="required",t={};t[k]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},
{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];t[m]=[{type:[f],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([k],["ga4"],[l]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},
{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:"mt_order mt_refund mt_view_item_list mt_select_item mt_view_item mt_add_to_wishlist mt_add_to_cart mt_view_cart mt_remove_from_cart mt_begin_checkout mt_add_shipping_info mt_add_payment_info mt_view_promotion mt_select_promotion".split(" ")}];Gb=function(a){if(!(a===$&&Ba)){a!==$&&(eb=[]);var b=e[$];b&&"function"===typeof b.push&&Ba&&(b.push=Ba,Ba=null);h(a);Fb=!0}}})();var Zb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},
{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(e).join(",")}catch(d){c=null}for(var g=[],n,h=0,m=a.length;h<m;h++){n=b[a[h].id];if(void 0===n)a:{n=a[h].globalVars;for(var k=c,f=0,v=n.length;f<v;f++){var s=n[f];if("string"===typeof s&&!(s in e)||"string"===typeof s.re&&(k&&-1===k.search(RegExp("($|,)"+s.re+"(,|^)","m"))||1===v)){n=!1;break a}}n=
!0}n&&(b[a[h].id]=!0,ha(a[h].id,g)||g.push(a[h].id))}return g}}(),Yc=Zb,ac=864E5,$b="tmr_floc",jc=null;(function(a){try{f.interestCohort&&"function"===typeof f.interestCohort&&f.interestCohort().then(function(a){jc={id:a.id,version:a.version};a=[a.id,a.version];var b=r();a=a.concat(b).join("|");Fa($b,a,{path:"/",expires:ac})},function(){})}catch(b){}})();var Hb=!1,Ya=null,Ra=null,Ib=!1,Cc;(function(){function a(){G.permissions.query({name:g}).then(function(a){b(a)})}function b(b){f&&e.clearTimeout(f);
try{var d=b.state;Ra=d in m?m[d]:h;Ib=d===n;Hb&&(c(Ib),f=e.setTimeout(a,k))}catch(g){}}function c(a){try{a?G[g].getCurrentPosition(d):d(null)}catch(b){}}function d(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,Ra);Ya=b.join("/")}catch(d){}else Ya=Ra}var g="geolocation",n="granted",h="u",m={denied:"d"};m[n]="g";m.prompt="p";var k=6E4,f=null;(function(){Ra=
h;d(null);try{g in G?G.permissions&&G.permissions.query({name:g}).then(function(a){b(a);a.onchange=function(){b(a)}}):Ra="n"}catch(a){}})();Cc=c})();var ua={support:!1},ua=function(){function a(){g(h)}function b(){g(h,y)}function c(a){a.persisted&&(q[h]=null,q[m]=null,g(h,p))}function d(){return k?!f[k]:null}function g(a,b){var c=r(),g="undefined"===typeof b?d():b;if(null===q[a])q[a]={ts:c,state:g,total:0};else{var e=q[a];if(e.state!==g&&!(e.state===y&&g!==p)){var h=c-e.ts,k=e.state;e.ts=c;e.state=
g;h<n||(k===p?(e.total+=h,t&&t(c,h)):k===s&&x&&x(c,h))}}}var n=5,h="auto",m="user",k=null,l=null,p=!0,s=!1,y=null;"hidden"in f?(k="hidden",l="visibilitychange"):"mozHidden"in f?(k="mozHidden",l="mozvisibilitychange"):"webkitHidden"in f?(k="webkitHidden",l="webkitvisibilitychange"):"msHidden"in f&&(k="msHidden",l="msvisibilitychange");var q={};q[h]=null;var t=q[m]=null,x=null;return{support:!!k,auto:function(d,g){t=d||null;x=g||null;k&&(a(),u(f,l,a));ra?(u(e,"pageshow",c),u(e,"pagehide",b)):(u(e,"beforeunload",
b),u(e,"unload",b))},set:function(a){g(m,!!a)},getLog:function(){var a=r(),b={},c,d;for(d in q)c=q[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();ua.auto();var Dc={enabled:!1};if(zc){var Ec=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");return{analyze:function(b){if(!b)return null;for(var c=[].slice.apply(b.elements),d=[],g=[],e=0,h=c.length;e<h;e++){var f;a:switch(f=c[e],f.tagName.toLowerCase()){case "button":f=
!1;break a;case "input":var k=f.type.toLowerCase();if(k&&-1===a.indexOf(k)){f=!1;break a}default:f=Pb(f,!1)&&f.name&&!1===f.disabled}f&&(d.push(c[e].name),g.push(c[e].type))}return{node:b,inputsName:d.length?d:null,inputsType:g.length?g:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");return"string"===typeof a?document.getElementById(a)||null:a instanceof HTMLElement?a:null}}}(),Dc=function(){function a(a){a=a||e.event;var c=(a.which||a.keyCode)===M;if("which"in
a&&a.which===D||"button"in a&&a.button&D||c){a:{a=a.target||a.srcElement;for(var c=0,d=h.length;c<d;c++){var f;b:{f=a;for(var A=h[c],F=0,H=A.types.length;F<H;F++){var w;c:{var r=f;w=A.types[F];var q=null;if(w.filter.tagName)for(var t=0,u=w.filter.tagName.length;t<u&&!(q=Ob(r,w.filter.tagName[t]));t++);else q=r;if(q){if(w.filter.attr)for(r in r=void 0,w.filter.attr)if(w.filter.attr.hasOwnProperty(r)&&(t=w.filter.attr[r],u=q[r],!0===t&&!u||!1===t&&u||ia(t)&&-1===t.indexOf(u))){w=null;break c}w={source:q,
type:w.type,detail:q.tagName}}else w=null}if(w){w.category=A.category;f=w;break b}}f=null}if(f){a=f;break a}}a=null}if(a){if(a.category===g){try{a.data=new URL(a.source.href)}catch(y){}if(!a.data)return}else if(a.category===n){if(a.data=Ec.analyze(Ec.getFormByInput(a.source)),!a.data)return}else return;c=E;if(c.enabled&&c.modes){d=0;for(f=c.modes.length;d<f;d++)if(A=a,F=c.modes[d],A.category===F.mode)if(A.category===g||A.category===n){if(F=F.categories,A.data){H=void 0;c:{H=0;for(w=F.length;H<w;H++){for(var q=
A,r=F[H],t={category:A.category},u=[],aa=0,z=r.types.length;aa<z;aa++){var B=r.types[aa],C=ja({type:r.category},t),N=s in B,J;v in B?J=b(q,B,C,v):N&&(J=ja({source:q.source,data:q.data,detail:B.type},C));if(J&&(!N||!b(q,B,C,s)))if(u.push(J),(B.rule&x)!==x)break}if(q=u.length?u:null){H=q;break c}}H=null}if(H){A=0;for(F=H.length;A<F;A++)c:{w=H[A];q={type:"sendEvent",category:"_"+w.category,action:w.detail};if(w.category===g&&(w.type===m||w.type===k)){if(q.label=w.data.href,!q.label)break c}else if(w.category===
l&&(q.label=w.data.node.action,!q.label))break c;_tmr.push(q)}}}}else p&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",A.type)}}}}function b(a,b,d,e){var g=!1,h=b[e];if(ia(h)){var f=b[e+"Rule"]||z;e=(f&r)===r;for(var f=(f&q)===q,k=0,n=h.length;k<n&&!(g=c(a,h[k]),e&&g);k++)if(f&&!g)return null}else g=c(a,h);return!g?null:ja({source:a.source,data:a.data,detail:b.type},d)}function c(a,b){var c=b.rule||z,g=(c&r)===r,c=(c&q)===q,e=!1,h;for(h in b)if(b.hasOwnProperty(h)&&"rule"!==
h){var e=b[h],f;switch(h){case "domain":f=jb(a.data);break;case "fileExtension":f=Rb(a.data.pathname,/.\.([^\.]+)$/,1)||"";break;default:f=a.data[h]}e=!0===e?!!(ia(f)?f.length:f):!1===e?!(ia(f)?f.length:f):d(f,e);if(g&&e)break;else if(c&&!e)return!1}return e}function d(a,b){var c=a;if(c)if(ia(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=z;if(O(d)&&!ia(d)){if(!ia(d.value))return!1;e=d.rule||e;d=d.value}a:{for(var g=(e&t)===t,h=(e&r)===r,e=(e&q)===q,f=!1,k=0,n=d.length;k<n;k++){var m=
d[k];if(m){var l="string"===typeof m;l&&!g&&(m=m.toLowerCase());var p=m instanceof RegExp;if(l||p){var f=!0,s;b:{s=c;for(var L=g,v=0,u=s.length;v<u;v++){var x=L?s[v]:s[v].toLowerCase();if(p&&m.test(x)||l&&m===x){s=!0;break b}}s=!1}if(h&&s){c=!0;break a}else if(e&&!s){c=!1;break a}}}}c=h?!1:e?f?!0:!1:void 0}return c}var g="click",n="submit",h=[{category:n,types:[{type:"button",filter:{tagName:["input","button"],attr:{type:["submit","image"]}}}]},{category:g,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],
m="file",k="resource",l="submit",v="filter",s="stop",r=1,q=2,t=4,x=8,z=r,E={enabled:!0,modes:[{mode:n,categories:[{category:l,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:r},{inputsName:["email"],inputsType:["email"],rule:r}],filterRule:q,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:g,categories:[{category:"contact",types:[{type:"email",filter:{protocol:["mailto:"]}},{type:"phone",filter:{protocol:["tel:"]}}]},{category:m,types:[{type:"file",
filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:k,types:[{type:"outgoing",rule:x,stop:{domain:[Hc(y.host,3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:kb("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},
stop:{href:[/password/]}},{type:"social",filter:{domain:kb("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},D=1,M=13;return{enabled:!0,start:function(){u(f,"click",a);u(f,"keypress",a)}}}();sd&&Dc.start()}var E=function(){function a(){b(null)}function b(a){g();a?(V=a===aa,sa=a):sa=S&&null!==V?V?aa:Y:f.visibilityState;
a=da();for(var b in ma)t(b,a)}function c(){if(!1!==P){N(e,$,ka);ka=null;e.clearInterval(ja);la=ja=null;N(f,O,ca);ca=null;S&&(N(e,W,fa),N(e,X,ga),ga=fa=null);n(!0);for(var a in ea){var b=a,c=ea[b];c&&(c=c.key,R(b),G(),delete ea[b],A(null,c))}I=null;na=[];wa=[];K={};ea={};ma={};P=!1}}function d(a,b,c){var d=a+"_"+b;if(d in K)return!1;var e=r(),g=da(),h=C(d,e,vb);b=K[d]={id:a||null,name:b,key:h,canUseInBackground:!!c,startTS:e,updateTS:g,timespent:{}};if(a)if(wa.push(d),d=b.canUseInBackground,b=ma[a]){if(c=
b.isActive,!c&&(e=I&&ha(a,I)))if(c=sa===aa||d)b.updateTS=g,b.isActive=!0}else e=I&&ha(a,I),c=sa===aa||d,ma[a]={isActive:e&&c,updateTS:g,timespent:{}};else na.push(d);return!0}function g(a,b){var c,d;2>arguments.length?(c=wa.concat(na),d=H):(c=[a+"_"+b],d=F);h(c,d)}function n(a,b,c){var d=!1,e=[],g=[];2>arguments.length?(e=wa.slice(),(d=!!arguments[0])&&(e=e.concat(na))):(d=a+"_"+b,-1!==wa.indexOf(d)?e=[d]:-1!==na.indexOf(d)&&(c?e=[d]:g=[d]));h(e,Z);h(g,F)}function h(a,b){var c=da(),d=[],e,g,h;e=0;
for(g=a.length;e<g;e++)h=a[e],-1!==wa.indexOf(h)?m(h,b,c):-1!==na.indexOf(h)&&d.push(h);e=0;for(g=d.length;e<g;e++)h=d[e],m(h,b,c);if(b===H&&(U=c,U-P>=pa)){for(var f in K)l(f);for(f in ea)if(c=f,d=ea[c])R(c),A(c,d.key);P=U}}function m(a,b,c){var d=K[a];if(d&&!1!==d.updateTS)if(d.timespent[sa]=(d.timespent[sa]||0)+(c-(d.updateTS||U)),-1!==na.indexOf(a)&&x(null,c),b===Z)d.updateTS=!1,l(a);else if(b===w){d.updateTS=c;var e;a:{if(b=K[a])for(e in b.timespent)if(b.timespent[e]>oa){e=!1;break a}e=!0}e?(k(a),
G()):l(a)}else d.updateTS=b===H?null:c,k(a),G()}function k(a,b,c){var d=K[a];if(!d)return null;var e=b||d.key;b=T[e];T[e]={uid:a,name:d.name,counterID:c||d.id||I,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=T[e].timespent;var d=d.timespent,g;for(g in d)a[g]=d[g];if(c&&(c=ma[c]))if(e=T[e]){e.common={};e=e.common;c=c.timespent;for(var h in c)e[h]=c[h]}return b||null}function l(a){var b=K[a];b&&(k(a),p(a,b.key))}function p(a,b){var c=T[b];if(c)if(ia(c.counterID)){var d=
T[b];if(d){var c=d.counterID,e=[],g,h,f,n;if(c){f=0;for(n=c.length;f<n;f++){h=c[f];g=C(b,h);e.push(g);h=k(a||d.uid,g,h);var m=void 0;h&&(m=T[g],E(m.timespent,h.timespent),h.common&&(m.common=m.common||{},E(m.common,h.common)))}}delete T[b];G();if(a&&a in K)if(d.isActive){y(a);f=0;for(n=c.length;f<n;f++)if(d=ma[c[f]])for(var l in d.timespent)d.timespent[l]=0}else q(a);f=0;for(n=e.length;f<n;f++)s(e[f])}}else if(l=T[b])(c=a&&a in K)&&!l.isActive&&q(a),e=s(b),c&&(e&&l.isActive)&&y(a)}function s(a){var b;
if(b=T[a]){var c=Q(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=Q(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+encodeURIComponent("TS:"+b.msg);M(B({id:b.id},J,!1,!1)+c);delete T[a];G();return!0}function y(a){if(a=K[a])for(var b in a.timespent)a.timespent[b]=0}function q(a){if(a in K){var b;-1!==(b=na.indexOf(a))&&na.splice(b,
1);if(-1!==(b=wa.indexOf(a)))if(wa.splice(b,1),b=K[a].id){var c=ma[b];if(c){var d=c.isActive;d&&D(c,da());d=z(b,a);d||(c.isActive=!1)}}delete K[a]}}function t(a,b){var c=ma[a];if(c){var d=I&&ha(a,I),e=z(a);c.isActive=d&&e;c.updateTS=b}}function x(a,b){if(a){var c=ma[a];c&&(c.isActive?D(c,da()):c.updateTS=b)}else for(c in ma)x(c,b)}function z(a,b){for(var c in K)if(c!==b&&K[c].id===a&&(sa===aa||K[c].canUseInBackground))return!0;return!1}function D(a,b){a&&(a.timespent[sa]=(a.timespent[sa]||0)+(b-a.updateTS),
a.updateTS=b)}function C(a){return[].join.call(arguments,"_")}function E(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function Q(a){var b=a[aa]||0,c=0,d;for(d in a)d!==aa&&(c+=a[d]);return{fg:b,bg:c}}function da(){return Math.floor(e.performance.now())}function G(){if(qa){var a={};a[ua]=T;a[va]=za;Ga(ta,ya(a)||"")}}function R(a){var b=ea[a];b&&(za[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function A(a,b){if(za[b]){var c;if(c=za[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");
c={id:c.counterID,msg:d}}else c=!1;c&&(d=";e="+encodeURIComponent("TS:"+c.msg),M(B({id:c.id},J,!1,!1)+d));!1!==c&&(delete za[b],G());if(c&&a&&(c=ea[a]))c.value=0}}var F=1,H=2,w=4,Z=8,$=ra?"pagehide":"unload",O="visibilitychange";"mozHidden"in f?O="mozvisibilitychange":"webkitHidden"in f?O="webkitvisibilitychange":"msHidden"in f&&(O="msvisibilitychange");var W="focus",X="blur";"onfocusin"in f&&(W="focusin",X="focusout");var aa="visible",Y="hidden",ba=["0"],S=!1,oa=100,pa=12E4,P=!1,U=!1,I=null,na=[],
wa=[],K={},sa,V=null,ja,la,ca,fa,ga,ka,ta="tmr_tslog",ua="activity",va="count",T={},ea={},za={},ma={};return{init:function(){if(qa){var a=Pa(xa(ta)||"{}");T=a[ua]||{};za=a[va]||{}}for(var b in T)p(null,b);for(b in za)A(null,b)},launch:function(){!1===P&&(P=da(),U=da(),sa=S&&null!==V?V?aa:Y:f.visibilityState,ka=c.bind(e),u(e,$,ka),la=a.bind(e),ja=e.setInterval(la,1E4),ca=b.bind(e,null),u(f,O,ca),S&&(fa=b.bind(e,aa),ga=b.bind(e,Y),u(e,W,fa),u(e,X,ga)))},enable:function(a){if(I){if(ha(a,I))return;h(na,
w)}else{for(var b=0,c=ba.length;b<c;b++)d(null,ba[b],!1);I=[]}I.push(a);t(a,da())},disable:function(a){if(I){var b;a:{b=0;for(var c=I.length;b<c;b++)if(I[b]==a)break a;b=-1}if(-1!==b&&(h(na,w),I.splice(b,1),b=da(),a=ma[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:g,stopActivity:n,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=ea[c]))if(c in ea)d=ea[c];else{d=r();var e=C(b,d,vb);d=ea[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,R(c),G())},defaultID:function(){return I?
I[0]:void 0}}}(),rb=!1,U=null,lc=function(){return U};(function(){function a(){var a=pa?oa(h):null;if(a)try{var a=decodeURIComponent(a).split(":"),b=a[0],c=parseInt(a[1]||"");if(b&&c&&!isNaN(c))return{fpid:b,ts:c}}catch(d){}return null}function b(){var a=xa(f);if(a)try{if((a=Pa(a))&&a.fpid&&a.time)return{fpid:a.fpid,ts:a.time}}catch(b){}return null}function c(){var a=xa(f);if(a)try{(a=Pa(a))&&(U=a.fpid||null)}catch(b){}e()}function d(){e()}function e(){Ga(m,ya({fpid:U,ts:r()}))}var f="rb_sync_id",
h="domain_sid",m="tmr_trgfpid";lc=function(){if("rb_sync"in window)try{U=window.rb_sync.id}catch(c){}if(!U){var d=b()||a();d&&(U=d.fpid)}return U};(function(){var e;if(!(e=b()))if(!(e=a()))a:{var g=qa?xa(m):null;if(g)try{if((g=Pa(g))&&g.fpid&&g.ts){e={fpid:g.fpid,ts:g.ts};break a}}catch(h){}e=null}if(e&&(U=e.fpid,864E5>r()-e.ts))return;pb("https://privacy-cs.mail.ru/static/sync-loader.js",c,d)})()})();var mc;(function(){var a=null,b=0;mc=function(){var c=r();if(b&&5E3>c-b)return a;b=c;return a=pa?
oa("vkidExtId"):null}})();var cd="60.6.0",bb=0,Na=0,vb=Tb(16),ba=null,la=null,X=null,Y=null,Ma=0,Ja="tmr_reqNum",R=null;pa&&(R=oa(Ja)||null,null!==R&&nb(Ja,ob));qa&&null===R&&(R=xa(Ja)||null);R=null===R?0:parseInt(R,10);qa&&Ga(Ja,R);var xd=["c8fdd627023b870e211a908648e1a5e1"],ca=(pa?oa("tmr_lvid"):null)||(qa?xa("tmr_lvid"):null),ta=(pa?oa("tmr_lvidTS"):null)||(qa?xa("tmr_lvidTS"):null);if(null===ca||-1===ca.search(/^[0-9a-fA-F]+$/)||Qb(ca,xd))ca=Tb(32),ta=null;Wb("tmr_lvid",ca);if(null===ta||-1===
ta.search(/^\d+$/))ta=""+r();Wb("tmr_lvidTS",ta);var P=0,C=[],va=[],gb=[],fb=[],db=[],cb={},ad="ontouchstart"in e||1<(G.maxTouchPoints||G.msMaxTouchPoints)?"1":"0",bd=e.devicePixelRatio||0,$c=function(){var a=e.screen;return a?a.width+"*"+a.height:""}(),ub=sb();(function(){var a=null;try{"ResizeObserver"in e&&(a=new ResizeObserver(function(){ub=sb()}),a.observe(f.documentElement))}catch(b){p&&console.warn("[TopMailRu] Error#1.33","Viewport size measurement error",b),a=null}a||u(e,"resize",function(){ub=
sb()})})();var Jb=e.performance||e.mozPerformance||e.msPerformance||e.webkitPerformance||{},Va=Jb.timing||{},wb=Jb.navigation||{},nc="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),yd="startTime duration firstInterimResponseStart redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd".split(" "),
Wa=Ia("navigationStart"),zd=Ia("domContentLoadedEventStart"),Ad=Ia("loadEventStart"),V=Wa,Xa=null,Ka=[];(function(){if(!Xa)try{for(var a=Jb.getEntriesByType("resource"),b,c=0,d=a.length;c<d;c++)if(b=a[c],b.name===document.currentScript.src){for(var e=b,f=yd,h=[],m=0,k=f.length;m<k;m++)h.push(Math.round(e[f[m]]||0));Xa=h.join("/");b.deliveryType&&Ka.push("cdt="+b.deliveryType);b.nextHopProtocol&&Ka.push("cnhp="+b.nextHopProtocol);if(b.encodedBodySize||b.decodedBodySize||b.transferSize)Ka.push("cs="+
[b.encodedBodySize||0,b.decodedBodySize||0,b.transferSize||0].join("-"))}}catch(l){p&&console.warn("[TopMailRu] Error#1.32","Resource timing error",l)}})();var oc="downlink downlinkMax effectiveType rtt saveData type".split(" "),fa,Kb;fa=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||P,e=c.title||null,f,h=Kb(b,{params:c.required,fn:c.fn});if(h.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<h.missed.length&&h.missed.slice(0,-1).join(", ")+
" and "||"")+h.missed.slice(-1)+" in "+a);else{var m=Kb(b,{params:c.optional,fn:c.fn});f=[].concat(h.values).concat(m.values);h=[].concat(h.missed).concat(m.missed);c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):h.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=h.length?"("+(1<h.length?h.slice(0,-1).join(", ")+" and "+h.slice(-1)+" are":h.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15",
"Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};Kb=function(a,b){var c=[],d=[],e,f,h;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{h=b.fn?b.fn:null,c.push(e+': "'+(h?h(e,f):f)+'"')}catch(m){console.warn("[TopMailRu] Error#1.16",m)}else d&&d.push(e);return{values:c,missed:d}};var z={},$a=null,Za=null,Eb=[];l.prototype.callbackOnReady=function(a){p&&fa("onReady",a,
{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),ra&&Eb.push(a))};l.prototype.pageView=function(a){Ha(a);a:if(a&&"object"===typeof a&&a.id){5>va.length&&!ha(a.id,va)&&(va.push(a.id),!1!==a.beat&&gb.push(a.id),C.push(a),La&&Xb(a));ra&&(cb[a.id]=ja(!0,{},a),cb[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(yb=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>fb.length&&!ha(a.id,fb)&&(!0===a.ecommerce||
b&&!c||b&&c||!1!==a.ecommerce&&!b&&(ha(a.id,ud)||!ha(a.id,vd)))){fb.push(a.id);if(b&&c){if(Fb&&(Gb(a.ecommerce),$!==a.ecommerce)){$=a.ecommerce;Q&&(Q=[0,0,$]);break a}$=a.ecommerce;Q&&(Q=[0,0,$])}b=[a.id];if(Fb)for(var c=0,d=eb.length;c<d;c++)Yb(b,eb[c])}a.timespent=Z&&(a.timespent||ha(a.id,rd)&&!1!==a.timespent);Z&&(a.timespent?E.enable(a.id):E.disable(a.id));Hb||(Hb=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&Cc(Ib);rb&&!ha(a.id,db)&&(db.push(a.id),bc([a.id]))}p&&fa("pageView",a,{title:"Page view",
optional:{url:y.href}});W(a)&&(M(B(a,"/counter",!1,!0)),Na=r())};l.prototype.reachGoal=function(a){Ha(a);p&&fa("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(W(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";M(B(a,J,!1,!0)+(";e="+encodeURIComponent("RG:"+b+"/"+a.goal)))}};var Ab="VALUE";l.prototype.itemView=function(a){p&&fa("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g,
" ")}});if(W(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0,f=kd(a.id,d,e,c);f&&this.reachGoal(f);(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||P)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");M(B(a,J,!1,!0)+(";e="+encodeURIComponent(b)))}};var ld="vk_ecom_";l.prototype.sendEvent=function(a){Ha(a);p&&fa("sendEvent",a,{title:"Send event",
value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(W(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");M(B(a,J,!1,!0)+(";e="+encodeURIComponent(b)))}};
l.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?p&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(ba=a,p&&console.info("[TopMailRu]: Global user ID = "+ba))}};l.prototype.getUserID=function(){return ba||0===ba?ba:void 0};l.prototype.deleteUserID=function(){ba=null;p&&console.info("[TopMailRu]: Reset global user ID to null")};l.prototype.setURL=function(a){null===a||!1===a||void 0===a?this.deleteURL():
"string"!==typeof a?p&&console.warn("[TopMailRu] Error#X.XX","Invalid url in setURL"):(X=a,p&&console.info("[TopMailRu]: Global url = "+X))};l.prototype.setReferrer=function(a){null===a||!1===a||void 0===a?this.deleteReferrer():"string"!==typeof a?p&&console.warn("[TopMailRu] Error#X.XX","Invalid referrer in setReferrer"):(Y=a,p&&console.info("[TopMailRu]: Global referrer = "+Y))};l.prototype.getURL=function(){return X?X:void 0};l.prototype.getReferrer=function(){return Y?Y:void 0};l.prototype.deleteURL=
function(){X=null;p&&console.info("[TopMailRu]: Reset global url to null")};l.prototype.deleteReferrer=function(){Y=null;p&&console.info("[TopMailRu]: Reset global referrer to null")};l.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(O(a)){try{la=ja(!0,{},a)}catch(b){p&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}p&&console.info("[TopMailRu]: Global user params = "+ya(la))}else p&&console.warn("[TopMailRu] Error#1.21",
"Invalid user params in setUserParams")};l.prototype.getUserParams=function(){var a=la?la:void 0;return a?ja(!0,{},a):void 0};l.prototype.deleteUserParams=function(){la=null;p&&console.info("[TopMailRu]: Reset global user params to null")};l.prototype.getClientID=function(){var a=ca;return a||0===a?a:void 0};l.prototype._MT_event=function(a,b,c){Ha(a);p&&fa(b,a,{title:c});W(a)&&M(B(a,J,!1,!0)+(";e="+encodeURIComponent("MT:/"+b)))};l.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent",
"VK Mini App Event")};var Lb=function(a,b){if(Z){var c=E.defaultID();W(a,c)&&(!O(a)||!("activity"in a&&a.activity)?p&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):E.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};l.prototype.startTimespent=function(a){Lb(a,null)};l.prototype.startForegroundTimespent=function(a){Lb(a,!1)};l.prototype.startAnytimeTimespent=function(a){Lb(a,!0)};l.prototype.updateTimespent=function(a){if(Z){var b=
E.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?E.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?E.updateActivity(a.id||b,""+a.activity):p&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};l.prototype.stopTimespent=function(a){if(Z){var b=E.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?E.stopActivity(!1):"number"===typeof a.activity||"string"===typeof a.activity?E.stopActivity(a.id||
b,""+a.activity,!1):p&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};l.prototype.incrementEventTimespent=function(a){if(Z){var b=E.defaultID();W(a,b)&&(!a||!("activity"in a&&a.activity)?p&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):E.incCount(a.id||b,""+a.activity))}};l.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===
a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "setURL":"url"in a&&
this.setURL(a.url);break;case "deleteURL":this.deleteURL();break;case "setReferrer":"referrer"in a&&this.setReferrer(a.referrer);break;case "deleteReferrer":this.deleteReferrer();break;case "miniAppEvent":this.miniAppEvent(a);break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);
break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else p&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else p&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};l.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var Fc=!1;l.prototype.onready=function(){Fc||(Fc=!0,!yb&&!La&&td(dd,ed),Gb($),fd())};var Db=!1;l.prototype.onload=function(){if(!Db){Db=!0;Ma=r();if(!Qa&&0<C.length){for(var a=";e="+
encodeURIComponent("RT/load")+";et="+Ma,b=0;b<C.length;b++)M(B(C[b],J,!0,!0)+a);Na=Ma}hd()}};l.prototype.beat=function(){var a;if(!zb&&bb){var b=r();if(!(12E4<b-bb)){if(12E4<b-Na){a=";e="+encodeURIComponent("RT/resend")+";et="+Ma;for(var c=0;c<C.length;c++)!1!==C[c].beat&&M(B(C[c],J,!1,!0)+a)}else 0<gb.length&&(a=";e="+encodeURIComponent("RT/beat")+";ids="+Ea(gb.join()),M(B({id:gb[0]},J,!1,!0)+a));Na=b}}};var Cb=!1;l.prototype.unload=function(){if(!Cb){Cb=!0;if(!Qa){var a;a=(a=cc())?r()-a:void 0;
a=";e="+encodeURIComponent("RT/unload")+";et="+r()+(a?";pvt="+encodeURIComponent(a):"");if(ua.support){var b=ua.getLog();a+=";vtauto="+b.auto}for(b=0;b<C.length;b++)M(B(C[b],J,!0,!0)+a)}ra&&(z.dcl3&&(clearTimeout(z.dcl3),delete z.dcl3),z.pvt2&&(clearTimeout(z.pvt2),delete z.pvt2),z.pvt15&&(clearTimeout(z.pvt15),delete z.pvt15),z.beat&&(clearInterval(z.beat),delete z.beat))}};l.prototype.activity=function(a){bb=r()};var Ca=_tmr;_tmr=new l;Z&&E.init();for(var D=0,Sa=Ca.length,ga;D<Sa;D++)(ga=Ca[D])&&
"object"===typeof ga&&Ha(ga);hb=(new Date).getTime();D=0;for(Sa=Ca.length;D<Sa;D++)ga=Ca[D],_tmr.processEvent(ga,1);Ta=(new Date).getTime();D=0;for(Sa=Ca.length;D<Sa;D++)ga=Ca[D],_tmr.processEvent(ga,-1);"complete"===f.readyState||"loading"!==f.readyState&&!f.documentElement.doScroll?(Za=zd,_tmr.onready(),tc()):f.addEventListener?u(f,"DOMContentLoaded",ab):f.attachEvent&&u(f,"readystatechange",ab);"complete"===f.readyState?($a=Ad,_tmr.onload()):ra?u(e,"pageshow",Bb):u(e,"load",Bb);ra?u(e,"pagehide",
Oa):(u(e,"unload",Oa),u(e,"beforeunload",Oa));sc();if(!zb)try{for(var Gc="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),Bd=function(a){u(f,a,function(){_tmr.activity(a)})},D=0;D<Gc.length;D++)Bd(Gc[D]);u(e,"scroll",function(){_tmr.activity("scallback")})}catch(Cd){p&&console.warn("[TopMailRu] Error#1.20",Cd)}Ua=(new Date).getTime()}})();
